#!/usr/bin/env python3
"""Generate one standalone .dc.html per screen in the source prototype.

The source file holds every screen in a single design doc. Each screen is a
top-level `<div data-screen-label="NN">` preceded by a caption block. This
splits them into standalone pages that share the source's head, helmet and
DCLogic script, so a screen opens at its own URL and still renders 1:1.

Generated files are overwritten on every run — edit the source, not them.

    python3 build-screens.py
"""

import html
import pathlib
import re
import sys

SOURCE = "Conversational Builder v2.dc.html"
ROOT = pathlib.Path(__file__).parent

CAPTION_OPEN = '  <div style="width: 1440px; display: flex; flex-direction: column; gap: 14px;">'
SCREEN_OPEN = re.compile(r'^  <div data-screen-label="(?P<label>[^"]+)"')
BLOCK_CLOSE = "  </div>"
BANNER = "<!-- GENERATED by build-screens.py from {} — do not edit directly. -->"


def find_blocks(lines):
    """Return (kind, label, start, end) for each top-level block, in order."""
    blocks = []
    open_at = None
    kind = label = None
    for i, line in enumerate(lines):
        if open_at is None:
            m = SCREEN_OPEN.match(line)
            if m:
                open_at, kind, label = i, "screen", m.group("label")
            elif line.rstrip("\n") == CAPTION_OPEN:
                open_at, kind, label = i, "caption", None
        elif line.rstrip("\n") == BLOCK_CLOSE:
            blocks.append((kind, label, open_at, i))
            open_at = kind = label = None
    if open_at is not None:
        sys.exit(f"error: unterminated {kind} block opened at line {open_at + 1}")
    return blocks


def caption_title(lines, start, end):
    """Pull the human label out of a caption block, e.g. 'Screen 01 — ...'."""
    for line in lines[start:end + 1]:
        m = re.search(r">(Screen\s+[^<]+)<", line)
        if m:
            return html.unescape(m.group(1)).strip()
    return None


def main():
    src = ROOT / SOURCE
    if not src.exists():
        sys.exit(f"error: {SOURCE} not found next to this script")

    lines = src.read_text(encoding="utf-8").splitlines(keepends=True)
    blocks = find_blocks(lines)
    screens = [b for b in blocks if b[0] == "screen"]
    if not screens:
        sys.exit("error: no data-screen-label blocks found")

    # Everything before the first block is shared head/helmet/page wrapper;
    # everything after the last is the closing wrapper and DCLogic script.
    prefix = "".join(lines[:blocks[0][2]])
    suffix = "".join(lines[blocks[-1][3] + 1:])

    written = []
    for kind, label, start, end in screens:
        # The caption block immediately preceding this screen, if any.
        caption = ""
        title = None
        idx = blocks.index((kind, label, start, end))
        if idx > 0 and blocks[idx - 1][0] == "caption":
            c_start, c_end = blocks[idx - 1][2], blocks[idx - 1][3]
            caption = "".join(lines[c_start:c_end + 1]) + "\n"
            title = caption_title(lines, c_start, c_end)

        title = title or f"Screen {label}"
        head = prefix.replace(
            "<script src=\"./support.js\"></script>",
            f"<title>{html.escape(title)}</title>\n<script src=\"./support.js\"></script>",
            1,
        )
        head = head.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + BANNER.format(SOURCE), 1)

        out = ROOT / f"screen-{label}.dc.html"
        out.write_text(head + caption + "".join(lines[start:end + 1]) + suffix, encoding="utf-8")
        written.append((out.name, title))

    for name, title in written:
        print(f"wrote {name}  ({title})")


if __name__ == "__main__":
    main()
