#!/usr/bin/env python3
"""Generate index.html — the prototype itself — from the screen in the source doc.

The source file is a design doc: the screen is a 1440x900 card sitting on a
black canvas, preceded by a caption block explaining it. That framing is right
for the doc and wrong for the prototype, so this strips it:

  * the caption block is dropped entirely
  * the page canvas loses its padding and inter-screen gap
  * the screen loses its fixed size, border and radius, and fills the viewport

The result is the screen as it would appear in the real product, and it is where
the prototype starts — every state is a query string on this one page.

index.html is overwritten on every run — edit the source, not it.

    python3 build-screens.py
"""

import html
import pathlib
import re
import sys

SOURCE = "Conversational Builder v2.dc.html"
OUTPUT = "index.html"
TITLE = "Conversational Builder v2 — FlowX AI-assisted builder"
ROOT = pathlib.Path(__file__).parent

CAPTION_OPEN = '  <div style="width: 1440px; display: flex; flex-direction: column; gap: 14px;">'
SCREEN_OPEN = re.compile(r'^  <div data-screen-label="(?P<label>[^"]+)"')
BLOCK_CLOSE = "  </div>"
BANNER = "<!-- GENERATED by build-screens.py from {} — do not edit directly. -->"

# (description, find, replace) applied to the shared page shell. Each must
# match, so a restyle of the source fails loudly here rather than silently
# producing a page that no longer fills the viewport.
PREFIX_EDITS = [
    (
        "page background and scroll",
        "html, body { margin: 0; padding: 0; background: #000000; }",
        "html, body { margin: 0; padding: 0; background: #0b1218; }",
    ),
    (
        "canvas padding and gap",
        "padding: 56px 56px 88px; display: flex; flex-direction: column; gap: 64px;",
        "padding: 0; display: flex; flex-direction: column;",
    ),
]

# Applied to the screen's own opening tag.
SCREEN_EDITS = [
    # Fill the viewport, but never below the size the layout was drawn for:
    # under 1440x900 the panes and table columns collide, so scroll instead.
    (
        "fixed size",
        "width: 1440px; height: 900px;",
        "width: 100%; height: 100vh; min-width: 1440px; min-height: 900px;",
    ),
    ("card border", "border: 1px solid #26313d; border-radius: 12px; ", ""),
    ("flex none", "flex: none; ", ""),
]


def apply_edits(text, edits, what):
    for description, find, replace in edits:
        if find not in text:
            sys.exit(
                f"error: could not apply '{description}' to the {what} — "
                f"{SOURCE} no longer contains:\n  {find}"
            )
        text = text.replace(find, replace, 1)
    return text


def find_blocks(lines):
    """Return (kind, label, start, end) for each top-level block, in order."""
    blocks = []
    open_at = None
    kind = label = None
    for i, line in enumerate(lines):
        if open_at is None:
            m = SCREEN_OPEN.match(line)
            if m:
                open_at, kind, label = i, "screen", m.group("label")
            elif line.rstrip("\n") == CAPTION_OPEN:
                open_at, kind, label = i, "caption", None
        elif line.rstrip("\n") == BLOCK_CLOSE:
            blocks.append((kind, label, open_at, i))
            open_at = kind = label = None
    if open_at is not None:
        sys.exit(f"error: unterminated {kind} block opened at line {open_at + 1}")
    return blocks


def main():
    src = ROOT / SOURCE
    if not src.exists():
        sys.exit(f"error: {SOURCE} not found next to this script")

    lines = src.read_text(encoding="utf-8").splitlines(keepends=True)
    blocks = find_blocks(lines)
    screens = [b for b in blocks if b[0] == "screen"]
    if not screens:
        sys.exit("error: no data-screen-label blocks found")
    # The prototype starts on one page, so one screen is all this can write. A
    # second screen needs a way in first — decide that, then teach it here.
    if len(screens) > 1:
        labels = ", ".join(b[1] for b in screens)
        sys.exit(
            f"error: {len(screens)} screens in {SOURCE} ({labels}), and {OUTPUT} is "
            f"one page — the prototype needs a way to reach a second screen first"
        )

    # Everything before the first block is shared head/helmet/canvas wrapper;
    # everything after the last is the closing wrapper and DCLogic script.
    prefix = apply_edits("".join(lines[:blocks[0][2]]), PREFIX_EDITS, "page shell")
    suffix = "".join(lines[blocks[-1][3] + 1:])

    _, label, start, end = screens[0]

    head = prefix.replace(
        '<script src="./support.js"></script>',
        f'<title>{html.escape(TITLE)}</title>\n<script src="./support.js"></script>',
        1,
    )
    head = head.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + BANNER.format(SOURCE), 1)

    screen = "".join(lines[start:end + 1])
    open_tag, rest = screen.split(">", 1)
    screen = apply_edits(open_tag, SCREEN_EDITS, f"screen {label}") + ">" + rest

    (ROOT / OUTPUT).write_text(head + screen + suffix, encoding="utf-8")
    print(f"wrote {OUTPUT}  (screen {label} — {TITLE})")


if __name__ == "__main__":
    main()
